source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.0'

# Use sqlite3 as the database for Active Record
gem 'sqlite3'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Latitude and Longitude calculation handling
gem 'geo-distance', '~> 0.2.0'

# Support multiple table inheritance
gem 'acts_as_relation', '~> 1.0'

group :development, :test do

  # RSPEC related gems
  gem 'rspec'
  gem 'rspec-rails'
  gem 'shoulda'

  # Object factories
  gem "factory_girl_rails", "~> 4.0"
end

# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]
